### ISSUE TITLE
Babel postinstall script prevents installing of redux-pouchdb-plus

### ISSUE THREAD

**Issue by timo-p** [medihack/redux-pouchdb-plus#10]
### How to reproduce
Try to install by running
```
npm install redux-pouchdb-plus
```
### What happens
Installation fails with error message
```
sh: babel: command not found
```
### Expected
redux-pouchdb-plus is installed correctly

**Comment by peponi** [comment]
@medihack can you plz merge the pull request

had the same issue, the package.json changes of @JMDidon solved it

**Comment by medihack** [comment]
Ok, done.

**Comment by gabrielmancini** [comment]
Error on the same place here:

```
735 warn react-native-maps@0.19.0 requires a peer of react@16.0.0 but none was installed.
736 warn react-native-maps@0.19.0 requires a peer of react-native@0.51.0 but none was installed.
737 warn redux-pouchdb-plus@0.9.0 requires a peer of immutable@^3.8.1 but none was installed.
738 warn redux-pouchdb-plus@0.9.0 requires a peer of pouchdb@^6.2.0 but none was installed.
739 warn transit-immutable-js@0.5.4 requires a peer of immutable@>= 3 but none was installed.
740 verbose stack Error: redux-pouchdb-plus@0.9.0 postinstall: `babel src --out-dir lib`
740 verbose stack Exit status 2
740 verbose stack     at EventEmitter.<anonymous> (/home/gabriel/.nvm/versions/node/v8.9.4/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
740 verbose stack     at emitTwo (events.js:126:13)
740 verbose stack     at EventEmitter.emit (events.js:214:7)
740 verbose stack     at ChildProcess.<anonymous> (/home/gabriel/.nvm/versions/node/v8.9.4/lib/node_modules/npm/lib/utils/spawn.js:40:14)
740 verbose stack     at emitTwo (events.js:126:13)
740 verbose stack     at ChildProcess.emit (events.js:214:7)
740 verbose stack     at maybeClose (internal/child_process.js:925:16)
740 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
741 verbose pkgid redux-pouchdb-plus@0.9.0
742 verbose cwd /home/gabriel/Development/marisa/hub/hub-app
743 verbose Linux 4.13.0-32-generic
744 verbose argv "/home/gabriel/.nvm/versions/node/v8.9.4/bin/node" "/home/gabriel/.nvm/versions/node/v8.9.4/bin/npm" "i" "redux-pouchdb-plus" "-S"
745 verbose node v8.9.4
746 verbose npm  v4.6.1
747 error code ELIFECYCLE
748 error errno 2
749 error redux-pouchdb-plus@0.9.0 postinstall: `babel src --out-dir lib`
749 error Exit status 2
750 error Failed at the redux-pouchdb-plus@0.9.0 postinstall script.
750 error This is probably not a problem with npm. There is likely additional logging output above.
751 verbose exit [ 2, true ]

```

**Comment by Sinamics** [comment]
Same error here. Even tried to install babel locally, but the problem still persist.

**Comment by michaeleboyce** [comment]
Same problem for me as well:

``` 
146 verbose stack Error: redux-pouchdb-plus@0.9.0 postinstall: `babel src --out-dir lib`
146 verbose stack Exit status 2
146 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
146 verbose stack     at EventEmitter.emit (events.js:160:13)
146 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
146 verbose stack     at ChildProcess.emit (events.js:160:13)
146 verbose stack     at maybeClose (internal/child_process.js:943:16)
146 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
147 verbose pkgid redux-pouchdb-plus@0.9.0
148 verbose cwd /Users/michaelboyce/Documents/Programming/braise
149 verbose Darwin 17.4.0
150 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "redux-pouchdb-plus"
151 verbose node v9.4.0
152 verbose npm  v5.6.0
153 error code ELIFECYCLE
154 error errno 2
155 error redux-pouchdb-plus@0.9.0 postinstall: `babel src --out-dir lib`
155 error Exit status 2
156 error Failed at the redux-pouchdb-plus@0.9.0 postinstall script.
156 error This is probably not a problem with npm. There is likely additional logging output above.
157 verbose exit [ 2, true ]
```

**Comment by Sinamics** [comment]
This is working for me.
```js
yarn add https://github.com/medihack/redux-pouchdb-plus.git
```

**Comment by medihack** [comment]
Should now work again when installing it directly from NPM. Can anyone confirm this? And sorry for the late solution. I promise that this library get's more love from me in the future.

**Comment by michaeleboyce** [comment]
Looks good to me now! Thank you!
